runtime: nodejs22

instance_class: F1

env_variables:
  NODE_ENV: "production"
  RESEND_API_KEY: "${_RESEND_API_KEY}"

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
