runtime: nodejs16

instance_class: F1

env_variables:
  NODE_ENV: "production"
  PORT: 8080

inbound_services:
- warmup

automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
