steps:
- name: node:22
  entrypoint: yarn
  args: ["install"]
- name: node:22
  entrypoint: yarn
  args: ["build"]
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: bash
  args:
    - "-c"
    - |
      sed -i "s|\$${_RESEND_API_KEY}|$$_RESEND_API_KEY|g" app.yaml
      gcloud app deploy --quiet
  env:
    - "_RESEND_API_KEY=${_RESEND_API_KEY}"
timeout: "1600s"
substitutions:
  _RESEND_API_KEY: ""
