import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { createGlobalStyle } from "styled-components";
import { AboutMeSection } from "../sections/about-me";
import { AcademicInfoSection } from "../sections/academic-info";
import { ContactSection } from "../sections/contact";
import { ExperienceSection } from "../sections/experience";
import { NameSection } from "../sections/name";
import { PersonalProjectsSection } from "../sections/personal-projects";
import { SkillsSection } from "../sections/skills";

const GlobalStyle = createGlobalStyle`
  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    font-family: 'Lato', sans-serif;
  }
  html {
    scroll-behavior: smooth;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NameSection />
        <AboutMeSection />
        <AcademicInfoSection />
        <SkillsSection />
        <ExperienceSection />
        <PersonalProjectsSection />
        <ContactSection />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <GlobalStyle />
    </div>
  );
};

export default Home;
